// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using WellWork.Infrastructure.Persistence;

#nullable disable

namespace WellWork.Infrastructure.Migrations
{
    [DbContext(typeof(WellWorkDbContext))]
    partial class WellWorkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WellWork.Domain.CheckIn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("SYS_GUID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TIMESTAMP WITH TIME ZONE")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Energy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("ENERGY");

                    b.Property<string>("Mood")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MOOD");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("NOTES");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("T_WELLWORK_CHECKINS", (string)null);
                });

            modelBuilder.Entity("WellWork.Domain.GeneratedMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("SYS_GUID()");

                    b.Property<Guid>("CheckInId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("CHECKIN_ID");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("NUMBER(5,4)")
                        .HasColumnName("CONFIDENCE");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("TIMESTAMP WITH TIME ZONE")
                        .HasColumnName("GENERATED_AT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("MESSAGE");

                    b.HasKey("Id");

                    b.HasIndex("CheckInId")
                        .IsUnique();

                    b.ToTable("T_WELLWORK_GENERATED_MESSAGES", (string)null);
                });

            modelBuilder.Entity("WellWork.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("SYS_GUID()");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("USERNAME");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("USERS", (string)null);
                });

            modelBuilder.Entity("WellWork.Domain.CheckIn", b =>
                {
                    b.HasOne("WellWork.Domain.User", "User")
                        .WithMany("CheckIns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WellWork.Domain.GeneratedMessage", b =>
                {
                    b.HasOne("WellWork.Domain.CheckIn", "CheckIn")
                        .WithOne("GeneratedMessage")
                        .HasForeignKey("WellWork.Domain.GeneratedMessage", "CheckInId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckIn");
                });

            modelBuilder.Entity("WellWork.Domain.CheckIn", b =>
                {
                    b.Navigation("GeneratedMessage");
                });

            modelBuilder.Entity("WellWork.Domain.User", b =>
                {
                    b.Navigation("CheckIns");
                });
#pragma warning restore 612, 618
        }
    }
}
